INSERT INTO "wearables" (clothing,body_part,temperature,gender)
          SELECT 'toque' AS 'clothing','head' AS 'body_part','-20..5' AS 'temperature','U' AS 'gender'
UNION ALL SELECT 'baseball cap','head','10..25','M'
UNION ALL SELECT 'sun hat','head','25..35','F'
UNION ALL SELECT 'bandana','head','10..20','U'
UNION ALL SELECT 'ear-muffs','ears','-20..5','U'
UNION ALL SELECT 'sunglasses','eyes','15..35','U'
UNION ALL SELECT 'scarf','neck','-20..5','F'
UNION ALL SELECT 'shawl','neck','-20..5','U'
UNION ALL SELECT 't-shirt','body','18..35','U'
UNION ALL SELECT 'tank top','body','18..35','F'
UNION ALL SELECT 'undershirt','body','-20..17','M'
UNION ALL SELECT 'longsleeve shirt','body','10..20','M'
UNION ALL SELECT 'button-up shirt','body','10..20','M'
UNION ALL SELECT 'blouse','body','10..20','F'
UNION ALL SELECT 'dress','body','18..27','F'
UNION ALL SELECT 'sweater','body','-20..12','U'
UNION ALL SELECT 'hooded sweater','body','-20..12','U'
UNION ALL SELECT 'cardigan','body','10..18','U'
UNION ALL SELECT 'Light jacket','body','10..15','U'
UNION ALL SELECT 'raincoat','body','0..40','U'
UNION ALL SELECT 'parka / heavy jacket','body','-20..5','U'
UNION ALL SELECT 'windbreaker','body','-20..13','U'
UNION ALL SELECT 'light gloves','hands','5..7','U'
UNION ALL SELECT 'heavy gloves','hands','-20..4','U'
UNION ALL SELECT 'shorts','legs','15..35','M'
UNION ALL SELECT 'skirt','legs','15..35','F'
UNION ALL SELECT 'long pants','legs','-5..16','U'
UNION ALL SELECT 'tights','legs','15..35','F'
UNION ALL SELECT 'snowpants','legs','-20..0','U'
UNION ALL SELECT 'boots','feet','-20..7','U'
UNION ALL SELECT 'sneakers','feet','8..23','U'
UNION ALL SELECT 'sandals','feet','24..35','U';